# This playbook was designed to be run with -K.
---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - finger
    - finger-server
    - xinetd
    - net-snmp
    - net-snmp-utils
    - mariadb
    - mariadb-server
    - tftp-server
  notify:
    - Enable MySQL
    - Start MySQL

# We want mysql to be started before we continue, because some stuff depends on
# it running
- meta: flush_handlers

- name: Configure xinetd services
  copy:
    src: "{{ item }}"
    dest: /etc/xinetd.d/{{ item }}
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart xinetd
  with_items:
    - finger
    - tftp

- name: Configure SNMP service
  copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart snmpd

- name: Allow finger and SNMP connections
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: true
    state: enabled
  notify:
    - Restart firewalld
  with_items:
    - 79/tcp
    - 161-162/udp
    - 20-21/tcp

- name: Turn off SELinux
  selinux:
    state: disabled

# User funs!
- import_tasks: users.yml

# Wordpress installation
- import_tasks: mysql.yml
- import_tasks: nginx.yml
- import_tasks: wordpress.yml