# This playbook was designed to be run with -K.
---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - finger
    - finger-server
    - xinetd
    - net-snmp
    - net-snmp-utils

- name: Configure finger service
  copy:
    src: finger
    dest: /etc/xinetd.d/finger
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart xinetd

- name: Configure SNMP service
  copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart snmpd

- name: Allow finger and SNMP connections
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: true
    state: enabled
  notify:
    - Restart firewalld
  with_items:
    - 79/tcp
    - 161-162/udp