---
- name: Set root password
  mysql_user:
    name: root 
    host: "{{ item }}"
    password: "{{ mysql_root_password | mandatory }}"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  notify:
    - Reload privilege tables

- name: Add .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600   

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  mysql_db:
    name: test
    state: absent
  notify:
    - Reload privilege tables