---
- name: Add nginx repository
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: Install nginx server
  yum:
    name: nginx
    state: present
    update_cache: yes

- name: Add document root
  file:
    path: /var/{{ item }}
    state: directory
  with_items:
    - www
    - www/html

- name: Add nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 644
  notify:
    - Restart nginx

- name: Install PHP packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - php-fpm
    - php-mysql

- name: Fix php.ini
  copy:
    src: php.ini
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart php processor

- name: Fix php-fpm www configuration
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart php processor

- name: Create virtual hosts directories
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  with_items:
    - sites-available
    - sites-enabled

- name: Generate nginx server block file
  template:
    src: server-block.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart nginx

- name: Enable nginx server
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart nginx

- name: Install Wordpress PHP packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - php-gd
    - php-mbstring
    - php-xml
    - php-xmlrpc
  notify:
    - Restart php processor

- name: Enable and start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Open firewall for HTTP
  firewalld:
    zone: public
    service: http
    permanent: true
    state: enabled
  notify:
    - Restart firewalld