---
- name: Restart xinetd
  systemd:
    name: xinetd
    state: restarted

- name: Restart firewalld
  systemd:
    name: firewalld
    state: restarted

- name: Restart snmpd
  systemd:
    name: snmpd
    state: restarted