---
# Finger and SNMP handlers
- name: Restart xinetd
  service:
    name: xinetd
    state: restarted

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

- name: Restart snmpd
  service:
    name: snmpd
    state: restarted

# MySQL handlers
- name: Enable MySQL
  service:
    name: mariadb
    enabled: yes

- name: Start MySQL
  service:
    name: mariadb
    state: started

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES

# nginx handlers
- name: Start nginx
  service:
    name: nginx
    state: started

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart php processor
  service:
    name: php-fpm
    state: restarted